### ISSUE TITLE
please add a version that is untouched and only English patched

### ISSUE THREAD

**Issue by KnivezOfficial** [FUComplete/Patch#13] opened 2022-01-04 00:31 UTC

**Comment by AsteriskAmpersand** [comment] 2022-01-04 01:22
You mean Capcom's officially released MHFU?

**Comment by KnivezOfficial** [comment] 2022-01-04 03:31
> You mean Capcom's officially released MHFU?

no, without the added dlc and bonuses, I like a Japanese english version because with the blood effect, their are some bugs with this v1.0 release, dlc quest that are cleared has no clear sign, and other graphical bugs

**Comment by IncognitoMan** [comment] 2022-01-04 05:27
> > You mean Capcom's officially released MHFU?
> 
> no, without the added dlc and bonuses, I like a Japanese english patched because with the blood effect, their are some bugs with this v1.0 release, dlc quest that are cleared has no clear sign, and other graphical bugs and missing challenge quest, it feels incomplete, I rather play a complete clean version

I really don't feel like segmenting out the patch further just to make one that defeats the purpose of said patch... I know people have been complaining about not being able to play with unpatched users on HV but until Zack implements what's needed to allow cross play... It'll remain like it is. You are more than welcome to rebuild the patch to only include English translation and nothing else but it's honestly not the goal of the project.

In regards to the DLC quests not showing as cleared this is both intended and no current way to resolve it. The DLC quests use a new range of IDs that wont mark clears in savedata to avoid any sort of issues. Maybe down the road there will be a fix but until I can be sure it wont overflow and cause savedata corruption it'll remain as such.

As for challenge quests... [I explained here a little about the issue](https://github.com/FUComplete/Patch/issues/9#issuecomment-977243310). To reiterate... the training hall code is a mess and have been struggling to come up with a way to make it work without breaking *something*... the solution will probably involve a challenge quest injector until a better solution is found.

You mentioned that there are graphical bugs? Are these new bugs or the current bugs listed in the issues? If the later they are all resolved for the next release... most of them were actually Capcom/localization bugs that existed in both P2G and FU. If they're new bugs, please create an issue detailing what is wrong so I can investigate it.

**Comment by IncognitoMan** [comment] 2022-01-04 05:50
Duplicate of #11

**Closed by IncognitoMan** 2022-01-04 05:50 UTC
